### ISSUE TITLE
Meeting 1/3/2015

### ISSUE THREAD

**Issue by Moorkopsoesje** [StevenReitsma/kaggle-national-data-science-bowl#16]
- Robbert is late so didn't participate

Done:
- @Lucivius minibatches multiple times iterated, fixed if folder doesn't exists. Java code removed from Python code.
- @Guardianofnature multiplying matrices to improve code so you don't need patches
- @Moorkopsoesje found partial_fit for RBM, still implementing
- @robbertvdg mwap mwap mwaww
- @Rahazan present classes in different order to classifier: random reader made, is really really slow, about 2 hours or longer, so not a viable option. Now try to randomize batch reader, or create smart sorting function, but shuffle large chunks instead of everything.
- @StevenReitsma continued with convolution networks, looked at data augmentation if more augmentation is more worth, it wasn't. Mailed Maaike and together with Tom looked at code to see why and couldn't find it. But now it seems to work.

To-do:
-  Presentation on Thursday, we will discuss this on Tuesday via Slack
- [x] @StevenReitsma finishes what he started with Tom, reshapes Tom's output, .....
- [x] @StevenReitsma  and @robbertvdg ..... so it can be pulled and put in the classifier, then it's done.
- [x] @Moorkopsoesje finish partial_fit RBM, visualize weights after. Then output needs to be reshaped in the same way as k-means output. 

Progress:
- About 15 days left!
